### ISSUE TITLE
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by anandkgpt03** [Privado-Inc/privado-core#968]
I am running privado scan on Android repo(main) in linux machine
`privado scan --skip-upload --debug --jvm-args "-Xms10g -Xmx42g" main`

The process is using a significant amount of virtual memory (VIRT)-73.7GB , non-swapped physical memory (RES) - 10.2GB, and CPU resources (%CPU) - 159.2

```
$ top  
 PID         USER      PR  NI    VIRT    RES    SHR     S   %CPU  %MEM     TIME+ COMMAND                                                                           
2749556     anandku+  20   0   73.7g     13.1g  33152  S   159.2     10.6        4:10.95 java
```

I also observed java process memory consumption increases as the android repo size increases.
Even with -Xmx42g memory provided - it throws Exception in thread "main" java.lang.OutOfMemoryError: Java heap space  Log: https://pastebin.com/8SAuxmFm 

Any reason why java process requires such a significant amount of memory in this context?

**Comment by pandurangpatil** [comment]
@anandkgpt03 We have identified a memory leak issue. Fix is on its way. Once the fix is rolled out, I will let you know in this ticket.

**Comment by pandurangpatil** [comment]
@anandkgpt03 with the latest released version should fix a few high memory issues. Hopefully, this release should fix the issue [v1.1.135](https://github.com/Privado-Inc/privado-core/releases/tag/v1.1.135). Reopen this ticket, if it doesn't.

If you are reopening the ticket add the following details.

1. Console logs that is getting displayed on the console.
2. Second run the scan with `--debug` option. You will find the debug log generated inside `<repo path>/.privado` folder with the name `debug.log`

**Comment by anandkgpt03** [comment]
@pandurangpatil I am still getting similar heap issue.

Please find the logs here as you asked:

1) Console Log: https://pastebin.com/eMd4mXXJ
2) Debug log: https://pastebin.com/FvGAmDJ2

**Comment by pandurangpatil** [comment]
@anandkgpt03 Thanks for the data points, the logs are helpful. We have identified multiple memory leak issues. Few of them got fixed in the last release. There few more complicated ones that we are working on as of now. It may take some time to fix these issues, we will keep you posted.

The repository you are trying to scan is open source or private? Checking if we can try that repo from our end.

**Comment by anandkgpt03** [comment]
@pandurangpatil The repository is private, so it wouldn't be possible to share the repo

**Comment by pandurangpatil** [comment]
@anandkgpt03 we have rolled out a couple of more fixes. Can you try once and let us know if the issue gets fixed.

**Comment by anandkgpt03** [comment]
Yeah, I am not getting these exceptions. Looks like the issue is fixed.

**Comment by pandurangpatil** [comment]
thanks @anandkgpt03 for confirmation. Closing this ticket
